apiVersion: v1
kind: ConfigMap
metadata:
  name: socket-firewall-config
  namespace: socket-firewall
data:
  SFW_HOSTNAME: "socket-firewall.socket-firewall.svc.cluster.local"
  SFW_HTTP_PORT: "8080"
  SFW_HTTPS_PORT: "8443"
  SFW_CA_CERT_PATH: "/app/certs/ca.crt"
  SFW_CA_KEY_PATH: "/app/certs/ca.key"
  SFW_DEBUG: "true"
